/**
*
*Copyright 2010 Microsoft Corp
*
*Licensed under the Apache License, Version 2.0 (the "License");
*you may not use this file except in compliance with the License.
*You may obtain a copy of the License at
*
*http://www.apache.org/licenses/LICENSE-2.0
*
*Unless required by applicable law or agreed to in writing, software
*distributed under the License is distributed on an "AS IS" BASIS,
*WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*See the License for the specific language governing permissions and
*limitations under the License.
*/
/**
* This code was generated by the tool 'odatagen'.
* Runtime Version:1.0
*
* Changes to this file may cause incorrect behavior and will be lost if
* the code is regenerated.
*/
/**
* Defines default Data Service URL for this proxy class
*/
#define DEFAULT_SERVICE_URL @""


#define DataServiceVersion @"2.0"

#import "ODataObject.h"
#import "ObjectContext.h"
#import "DataServiceQuery.h"
#import "ODataGUID.h"
#import "ODataBool.h"
#import  "mProperties.h"
#import "ODataServiceException.h"


/**
 * @interface:HighScoreDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface PineHighScore_DataTransferObjects_HighScoreDto : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Guid
	*/
	NSString *m_ID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_UserId;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_GameId;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_UserName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_AvatarUrl;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_Token;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_Currency01;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_Currency02;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_Currency03;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ArchivementCount01;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ArchivementCount02;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ArchivementCount03;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ArchivementCount04;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ArchivementCount05;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_HighScore01;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_HighScore02;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_HighScore03;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_HighScore04;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_HighScore05;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_HighScore06;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_HighScore07;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_HighScore08;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_HighScore09;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_HighScore10;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_DailyHighScore01;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_DailyHighScore02;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_DailyHighScore03;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_DailyHighScore04;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_DailyHighScore05;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_DailyHighScore06;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_DailyHighScore07;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_DailyHighScore08;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_DailyHighScore09;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_DailyHighScore10;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_WeeklyHighScore01;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_WeeklyHighScore02;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_WeeklyHighScore03;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_WeeklyHighScore04;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_WeeklyHighScore05;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_WeeklyHighScore06;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_WeeklyHighScore07;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_WeeklyHighScore08;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_WeeklyHighScore09;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_WeeklyHighScore10;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastDailyHighScore01;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastDailyHighScore02;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastDailyHighScore03;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastDailyHighScore04;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastDailyHighScore05;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastDailyHighScore06;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastDailyHighScore07;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastDailyHighScore08;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastDailyHighScore09;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastDailyHighScore10;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastWeeklyHighScore01;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastWeeklyHighScore02;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastWeeklyHighScore03;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastWeeklyHighScore04;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastWeeklyHighScore05;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastWeeklyHighScore06;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastWeeklyHighScore07;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastWeeklyHighScore08;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastWeeklyHighScore09;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_LastWeeklyHighScore10;
	
}

@property ( nonatomic , retain ,  getter=getID , setter=setID :)NSString *m_ID;
@property ( nonatomic , retain , getter=getUserId , setter=setUserId :)NSNumber *m_UserId;
@property ( nonatomic , retain , getter=getGameId , setter=setGameId :)NSNumber *m_GameId;
@property ( nonatomic , retain , getter=getUserName , setter=setUserName :) NSString *m_UserName;
@property ( nonatomic , retain , getter=getAvatarUrl , setter=setAvatarUrl :) NSString *m_AvatarUrl;
@property ( nonatomic , retain , getter=getToken , setter=setToken :) NSString *m_Token;
@property ( nonatomic , retain , getter=getCurrency01 , setter=setCurrency01 :)NSNumber *m_Currency01;
@property ( nonatomic , retain , getter=getCurrency02 , setter=setCurrency02 :)NSNumber *m_Currency02;
@property ( nonatomic , retain , getter=getCurrency03 , setter=setCurrency03 :)NSNumber *m_Currency03;
@property ( nonatomic , retain , getter=getArchivementCount01 , setter=setArchivementCount01 :)NSNumber *m_ArchivementCount01;
@property ( nonatomic , retain , getter=getArchivementCount02 , setter=setArchivementCount02 :)NSNumber *m_ArchivementCount02;
@property ( nonatomic , retain , getter=getArchivementCount03 , setter=setArchivementCount03 :)NSNumber *m_ArchivementCount03;
@property ( nonatomic , retain , getter=getArchivementCount04 , setter=setArchivementCount04 :)NSNumber *m_ArchivementCount04;
@property ( nonatomic , retain , getter=getArchivementCount05 , setter=setArchivementCount05 :)NSNumber *m_ArchivementCount05;
@property ( nonatomic , retain , getter=getHighScore01 , setter=setHighScore01 :)NSDecimalNumber *m_HighScore01;
@property ( nonatomic , retain , getter=getHighScore02 , setter=setHighScore02 :)NSDecimalNumber *m_HighScore02;
@property ( nonatomic , retain , getter=getHighScore03 , setter=setHighScore03 :)NSDecimalNumber *m_HighScore03;
@property ( nonatomic , retain , getter=getHighScore04 , setter=setHighScore04 :)NSDecimalNumber *m_HighScore04;
@property ( nonatomic , retain , getter=getHighScore05 , setter=setHighScore05 :)NSDecimalNumber *m_HighScore05;
@property ( nonatomic , retain , getter=getHighScore06 , setter=setHighScore06 :)NSDecimalNumber *m_HighScore06;
@property ( nonatomic , retain , getter=getHighScore07 , setter=setHighScore07 :)NSDecimalNumber *m_HighScore07;
@property ( nonatomic , retain , getter=getHighScore08 , setter=setHighScore08 :)NSDecimalNumber *m_HighScore08;
@property ( nonatomic , retain , getter=getHighScore09 , setter=setHighScore09 :)NSDecimalNumber *m_HighScore09;
@property ( nonatomic , retain , getter=getHighScore10 , setter=setHighScore10 :)NSDecimalNumber *m_HighScore10;
@property ( nonatomic , retain , getter=getDailyHighScore01 , setter=setDailyHighScore01 :)NSDecimalNumber *m_DailyHighScore01;
@property ( nonatomic , retain , getter=getDailyHighScore02 , setter=setDailyHighScore02 :)NSDecimalNumber *m_DailyHighScore02;
@property ( nonatomic , retain , getter=getDailyHighScore03 , setter=setDailyHighScore03 :)NSDecimalNumber *m_DailyHighScore03;
@property ( nonatomic , retain , getter=getDailyHighScore04 , setter=setDailyHighScore04 :)NSDecimalNumber *m_DailyHighScore04;
@property ( nonatomic , retain , getter=getDailyHighScore05 , setter=setDailyHighScore05 :)NSDecimalNumber *m_DailyHighScore05;
@property ( nonatomic , retain , getter=getDailyHighScore06 , setter=setDailyHighScore06 :)NSDecimalNumber *m_DailyHighScore06;
@property ( nonatomic , retain , getter=getDailyHighScore07 , setter=setDailyHighScore07 :)NSDecimalNumber *m_DailyHighScore07;
@property ( nonatomic , retain , getter=getDailyHighScore08 , setter=setDailyHighScore08 :)NSDecimalNumber *m_DailyHighScore08;
@property ( nonatomic , retain , getter=getDailyHighScore09 , setter=setDailyHighScore09 :)NSDecimalNumber *m_DailyHighScore09;
@property ( nonatomic , retain , getter=getDailyHighScore10 , setter=setDailyHighScore10 :)NSDecimalNumber *m_DailyHighScore10;
@property ( nonatomic , retain , getter=getWeeklyHighScore01 , setter=setWeeklyHighScore01 :)NSDecimalNumber *m_WeeklyHighScore01;
@property ( nonatomic , retain , getter=getWeeklyHighScore02 , setter=setWeeklyHighScore02 :)NSDecimalNumber *m_WeeklyHighScore02;
@property ( nonatomic , retain , getter=getWeeklyHighScore03 , setter=setWeeklyHighScore03 :)NSDecimalNumber *m_WeeklyHighScore03;
@property ( nonatomic , retain , getter=getWeeklyHighScore04 , setter=setWeeklyHighScore04 :)NSDecimalNumber *m_WeeklyHighScore04;
@property ( nonatomic , retain , getter=getWeeklyHighScore05 , setter=setWeeklyHighScore05 :)NSDecimalNumber *m_WeeklyHighScore05;
@property ( nonatomic , retain , getter=getWeeklyHighScore06 , setter=setWeeklyHighScore06 :)NSDecimalNumber *m_WeeklyHighScore06;
@property ( nonatomic , retain , getter=getWeeklyHighScore07 , setter=setWeeklyHighScore07 :)NSDecimalNumber *m_WeeklyHighScore07;
@property ( nonatomic , retain , getter=getWeeklyHighScore08 , setter=setWeeklyHighScore08 :)NSDecimalNumber *m_WeeklyHighScore08;
@property ( nonatomic , retain , getter=getWeeklyHighScore09 , setter=setWeeklyHighScore09 :)NSDecimalNumber *m_WeeklyHighScore09;
@property ( nonatomic , retain , getter=getWeeklyHighScore10 , setter=setWeeklyHighScore10 :)NSDecimalNumber *m_WeeklyHighScore10;
@property ( nonatomic , retain , getter=getLastDailyHighScore01 , setter=setLastDailyHighScore01 :)NSDecimalNumber *m_LastDailyHighScore01;
@property ( nonatomic , retain , getter=getLastDailyHighScore02 , setter=setLastDailyHighScore02 :)NSDecimalNumber *m_LastDailyHighScore02;
@property ( nonatomic , retain , getter=getLastDailyHighScore03 , setter=setLastDailyHighScore03 :)NSDecimalNumber *m_LastDailyHighScore03;
@property ( nonatomic , retain , getter=getLastDailyHighScore04 , setter=setLastDailyHighScore04 :)NSDecimalNumber *m_LastDailyHighScore04;
@property ( nonatomic , retain , getter=getLastDailyHighScore05 , setter=setLastDailyHighScore05 :)NSDecimalNumber *m_LastDailyHighScore05;
@property ( nonatomic , retain , getter=getLastDailyHighScore06 , setter=setLastDailyHighScore06 :)NSDecimalNumber *m_LastDailyHighScore06;
@property ( nonatomic , retain , getter=getLastDailyHighScore07 , setter=setLastDailyHighScore07 :)NSDecimalNumber *m_LastDailyHighScore07;
@property ( nonatomic , retain , getter=getLastDailyHighScore08 , setter=setLastDailyHighScore08 :)NSDecimalNumber *m_LastDailyHighScore08;
@property ( nonatomic , retain , getter=getLastDailyHighScore09 , setter=setLastDailyHighScore09 :)NSDecimalNumber *m_LastDailyHighScore09;
@property ( nonatomic , retain , getter=getLastDailyHighScore10 , setter=setLastDailyHighScore10 :)NSDecimalNumber *m_LastDailyHighScore10;
@property ( nonatomic , retain , getter=getLastWeeklyHighScore01 , setter=setLastWeeklyHighScore01 :)NSDecimalNumber *m_LastWeeklyHighScore01;
@property ( nonatomic , retain , getter=getLastWeeklyHighScore02 , setter=setLastWeeklyHighScore02 :)NSDecimalNumber *m_LastWeeklyHighScore02;
@property ( nonatomic , retain , getter=getLastWeeklyHighScore03 , setter=setLastWeeklyHighScore03 :)NSDecimalNumber *m_LastWeeklyHighScore03;
@property ( nonatomic , retain , getter=getLastWeeklyHighScore04 , setter=setLastWeeklyHighScore04 :)NSDecimalNumber *m_LastWeeklyHighScore04;
@property ( nonatomic , retain , getter=getLastWeeklyHighScore05 , setter=setLastWeeklyHighScore05 :)NSDecimalNumber *m_LastWeeklyHighScore05;
@property ( nonatomic , retain , getter=getLastWeeklyHighScore06 , setter=setLastWeeklyHighScore06 :)NSDecimalNumber *m_LastWeeklyHighScore06;
@property ( nonatomic , retain , getter=getLastWeeklyHighScore07 , setter=setLastWeeklyHighScore07 :)NSDecimalNumber *m_LastWeeklyHighScore07;
@property ( nonatomic , retain , getter=getLastWeeklyHighScore08 , setter=setLastWeeklyHighScore08 :)NSDecimalNumber *m_LastWeeklyHighScore08;
@property ( nonatomic , retain , getter=getLastWeeklyHighScore09 , setter=setLastWeeklyHighScore09 :)NSDecimalNumber *m_LastWeeklyHighScore09;
@property ( nonatomic , retain , getter=getLastWeeklyHighScore10 , setter=setLastWeeklyHighScore10 :)NSDecimalNumber *m_LastWeeklyHighScore10;

+ (id) CreateHighScoreDtoWithid:(NSString *)aID userid:(NSNumber *)aUserId gameid:(NSNumber *)aGameId;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:SentRequestDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface PineHighScore_DataTransferObjects_SentRequestDto : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_ID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_GameId;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_Sender;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_Receiver;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_RequestType;
	
}

@property ( nonatomic , retain , getter=getID , setter=setID :)NSNumber *m_ID;
@property ( nonatomic , retain , getter=getGameId , setter=setGameId :)NSNumber *m_GameId;
@property ( nonatomic , retain , getter=getSender , setter=setSender :)NSNumber *m_Sender;
@property ( nonatomic , retain , getter=getReceiver , setter=setReceiver :)NSNumber *m_Receiver;
@property ( nonatomic , retain , getter=getRequestType , setter=setRequestType :)NSNumber *m_RequestType;

+ (id) CreateSentRequestDtoWithid:(NSNumber *)aID gameid:(NSNumber *)aGameId sender:(NSNumber *)aSender receiver:(NSNumber *)aReceiver requesttype:(NSNumber *)aRequestType;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:RankedHighScoreDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface PineHighScore_DataTransferObjects_RankedHighScoreDto : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Guid
	*/
	NSString *m_ID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_Rank;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_UserId;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_Score;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_TopScore;
	
}

@property ( nonatomic , retain ,  getter=getID , setter=setID :)NSString *m_ID;
@property ( nonatomic , retain , getter=getRank , setter=setRank :)NSNumber *m_Rank;
@property ( nonatomic , retain , getter=getUserId , setter=setUserId :)NSNumber *m_UserId;
@property ( nonatomic , retain , getter=getScore , setter=setScore :)NSDecimalNumber *m_Score;
@property ( nonatomic , retain , getter=getTopScore , setter=setTopScore :)NSDecimalNumber *m_TopScore;

+ (id) CreateRankedHighScoreDtoWithid:(NSString *)aID rank:(NSNumber *)aRank userid:(NSNumber *)aUserId;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:TopScoreDto
 * @Type:EntityType
 
 * @key:ID* 
 */
@interface PineHighScore_DataTransferObjects_TopScoreDto : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Guid
	*/
	NSString *m_ID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int64
	*/
	NSNumber *m_UserId;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_UserName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:
	* @FixedLength:
	*/
	NSString *m_AvatarUrl;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Double
	*/
	NSDecimalNumber *m_Score;
	
}

@property ( nonatomic , retain ,  getter=getID , setter=setID :)NSString *m_ID;
@property ( nonatomic , retain , getter=getUserId , setter=setUserId :)NSNumber *m_UserId;
@property ( nonatomic , retain , getter=getUserName , setter=setUserName :) NSString *m_UserName;
@property ( nonatomic , retain , getter=getAvatarUrl , setter=setAvatarUrl :) NSString *m_AvatarUrl;
@property ( nonatomic , retain , getter=getScore , setter=setScore :)NSDecimalNumber *m_Score;

+ (id) CreateTopScoreDtoWithid:(NSString *)aID userid:(NSNumber *)aUserId;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * Container interface PineHighScoreContext, Namespace: PineHighScore.DataTransferObjects
 */
@interface PineHighScoreContext : ObjectContext
{
	 NSString *m_OData_etag;
	 DataServiceQuery *m_HighScores;
	 DataServiceQuery *m_MyRequests;
	 DataServiceQuery *m_RankedScores;
	 DataServiceQuery *m_TopScores;
	
}

@property ( nonatomic , retain , getter=getEtag , setter=setEtag: )NSString *m_OData_etag;
@property ( nonatomic , retain , getter=getHighScores , setter=setHighScores :) DataServiceQuery *m_HighScores;
@property ( nonatomic , retain , getter=getMyRequests , setter=setMyRequests: ) DataServiceQuery *m_MyRequests;
@property ( nonatomic , retain , getter=getRankedScores , setter=setRankedScores: ) DataServiceQuery *m_RankedScores;
@property ( nonatomic , retain , getter=getTopScores , setter=setTopScores: ) DataServiceQuery *m_TopScores;

- (id) init;
- (id) initWithUri:(NSString*)anUri credential:(id)acredential;
- (id) highscores;
- (id) myrequests;
- (id) rankedscores;
- (id) topscores;
- (void) addToHighScores:(id)anObject;
- (void) addToMyRequests:(id)anObject;
- (void) addToRankedScores:(id)anObject;
- (void) addToTopScores:(id)anObject;

@end
