/**
*
*Copyright 2010 Microsoft Corp
*
*Licensed under the Apache License, Version 2.0 (the "License");
*you may not use this file except in compliance with the License.
*You may obtain a copy of the License at
*
*http://www.apache.org/licenses/LICENSE-2.0
*
*Unless required by applicable law or agreed to in writing, software
*distributed under the License is distributed on an "AS IS" BASIS,
*WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*See the License for the specific language governing permissions and
*limitations under the License.
*/
/**
* This code was generated by the tool 'odatagen'.
* Runtime Version:1.0
*
* Changes to this file may cause incorrect behavior and will be lost if
* the code is regenerated.
*/
#import "PineHighScoreContext.h"
/**
 * @interface:HighScoreDto
 * @key:ID
 */
@implementation PineHighScore_DataTransferObjects_HighScoreDto
	@synthesize m_ID;
	@synthesize m_UserId;
	@synthesize m_GameId;
	@synthesize m_UserName;
	@synthesize m_AvatarUrl;
	@synthesize m_Token;
	@synthesize m_Currency01;
	@synthesize m_Currency02;
	@synthesize m_Currency03;
	@synthesize m_ArchivementCount01;
	@synthesize m_ArchivementCount02;
	@synthesize m_ArchivementCount03;
	@synthesize m_ArchivementCount04;
	@synthesize m_ArchivementCount05;
	@synthesize m_HighScore01;
	@synthesize m_HighScore02;
	@synthesize m_HighScore03;
	@synthesize m_HighScore04;
	@synthesize m_HighScore05;
	@synthesize m_HighScore06;
	@synthesize m_HighScore07;
	@synthesize m_HighScore08;
	@synthesize m_HighScore09;
	@synthesize m_HighScore10;
	@synthesize m_DailyHighScore01;
	@synthesize m_DailyHighScore02;
	@synthesize m_DailyHighScore03;
	@synthesize m_DailyHighScore04;
	@synthesize m_DailyHighScore05;
	@synthesize m_DailyHighScore06;
	@synthesize m_DailyHighScore07;
	@synthesize m_DailyHighScore08;
	@synthesize m_DailyHighScore09;
	@synthesize m_DailyHighScore10;
	@synthesize m_WeeklyHighScore01;
	@synthesize m_WeeklyHighScore02;
	@synthesize m_WeeklyHighScore03;
	@synthesize m_WeeklyHighScore04;
	@synthesize m_WeeklyHighScore05;
	@synthesize m_WeeklyHighScore06;
	@synthesize m_WeeklyHighScore07;
	@synthesize m_WeeklyHighScore08;
	@synthesize m_WeeklyHighScore09;
	@synthesize m_WeeklyHighScore10;
	@synthesize m_LastDailyHighScore01;
	@synthesize m_LastDailyHighScore02;
	@synthesize m_LastDailyHighScore03;
	@synthesize m_LastDailyHighScore04;
	@synthesize m_LastDailyHighScore05;
	@synthesize m_LastDailyHighScore06;
	@synthesize m_LastDailyHighScore07;
	@synthesize m_LastDailyHighScore08;
	@synthesize m_LastDailyHighScore09;
	@synthesize m_LastDailyHighScore10;
	@synthesize m_LastWeeklyHighScore01;
	@synthesize m_LastWeeklyHighScore02;
	@synthesize m_LastWeeklyHighScore03;
	@synthesize m_LastWeeklyHighScore04;
	@synthesize m_LastWeeklyHighScore05;
	@synthesize m_LastWeeklyHighScore06;
	@synthesize m_LastWeeklyHighScore07;
	@synthesize m_LastWeeklyHighScore08;
	@synthesize m_LastWeeklyHighScore09;
	@synthesize m_LastWeeklyHighScore10;

/**
 *Method to create an instance of HighScoreDto
 */
+ (id) CreateHighScoreDtoWithid:(NSString *)aID userid:(NSNumber *)aUserId gameid:(NSNumber *)aGameId
{
	PineHighScore_DataTransferObjects_HighScoreDto *aHighScoreDto = [[PineHighScore_DataTransferObjects_HighScoreDto alloc]init];
	
	aHighScoreDto.m_ID = aID;

	
	aHighScoreDto.m_UserId = aUserId;

	
	aHighScoreDto.m_GameId = aGameId;

	return aHighScoreDto;
}
/**
 * Initialising object for HighScoreDto
 */
- (id) init
{
	self=[self initWithUri:nil];
	return self;
}

- (id) initWithUri:(NSString*)anUri 
{
	if(self=[super initWithUri:anUri])
	{
		[self setBaseURI:anUri];
		m_OData_hasStream.booleanvalue=NO;
		mProperties *obj;
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Guid" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_ID"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_UserId"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_GameId"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.String" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_UserName"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.String" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_AvatarUrl"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.String" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_Token"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_Currency01"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_Currency02"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_Currency03"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int32" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_ArchivementCount01"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int32" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_ArchivementCount02"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int32" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_ArchivementCount03"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int32" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_ArchivementCount04"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int32" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_ArchivementCount05"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_HighScore01"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_HighScore02"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_HighScore03"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_HighScore04"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_HighScore05"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_HighScore06"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_HighScore07"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_HighScore08"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_HighScore09"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_HighScore10"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_DailyHighScore01"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_DailyHighScore02"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_DailyHighScore03"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_DailyHighScore04"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_DailyHighScore05"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_DailyHighScore06"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_DailyHighScore07"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_DailyHighScore08"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_DailyHighScore09"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_DailyHighScore10"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_WeeklyHighScore01"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_WeeklyHighScore02"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_WeeklyHighScore03"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_WeeklyHighScore04"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_WeeklyHighScore05"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_WeeklyHighScore06"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_WeeklyHighScore07"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_WeeklyHighScore08"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_WeeklyHighScore09"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_WeeklyHighScore10"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastDailyHighScore01"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastDailyHighScore02"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastDailyHighScore03"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastDailyHighScore04"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastDailyHighScore05"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastDailyHighScore06"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastDailyHighScore07"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastDailyHighScore08"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastDailyHighScore09"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastDailyHighScore10"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastWeeklyHighScore01"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastWeeklyHighScore02"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastWeeklyHighScore03"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastWeeklyHighScore04"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastWeeklyHighScore05"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastWeeklyHighScore06"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastWeeklyHighScore07"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastWeeklyHighScore08"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastWeeklyHighScore09"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_LastWeeklyHighScore10"];
		[obj release];
		

		NSMutableArray *anEntityKey=[[NSMutableArray alloc]init];
		[anEntityKey addObject:@"ID"];
		[m_OData_entityKey setObject:anEntityKey forKey:@"HighScoreDto"];
		[anEntityKey release];
	}
	return self;
}

-(NSMutableArray *)getSyndicateArray
{
	NSMutableArray *syndicateArray=[[NSMutableArray alloc]init];
	
	return [syndicateArray autorelease];
}
-(PineHighScore_DataTransferObjects_HighScoreDto *)getDeepCopy
{
	PineHighScore_DataTransferObjects_HighScoreDto *obj=[[PineHighScore_DataTransferObjects_HighScoreDto alloc]initWithUri:[self getBaseURI]];
	[obj setID:[self getID]];
	[obj setUserId:[self getUserId]];
	[obj setGameId:[self getGameId]];
	[obj setUserName:[self getUserName]];
	[obj setAvatarUrl:[self getAvatarUrl]];
	[obj setToken:[self getToken]];
	[obj setCurrency01:[self getCurrency01]];
	[obj setCurrency02:[self getCurrency02]];
	[obj setCurrency03:[self getCurrency03]];
	[obj setArchivementCount01:[self getArchivementCount01]];
	[obj setArchivementCount02:[self getArchivementCount02]];
	[obj setArchivementCount03:[self getArchivementCount03]];
	[obj setArchivementCount04:[self getArchivementCount04]];
	[obj setArchivementCount05:[self getArchivementCount05]];
	[obj setHighScore01:[self getHighScore01]];
	[obj setHighScore02:[self getHighScore02]];
	[obj setHighScore03:[self getHighScore03]];
	[obj setHighScore04:[self getHighScore04]];
	[obj setHighScore05:[self getHighScore05]];
	[obj setHighScore06:[self getHighScore06]];
	[obj setHighScore07:[self getHighScore07]];
	[obj setHighScore08:[self getHighScore08]];
	[obj setHighScore09:[self getHighScore09]];
	[obj setHighScore10:[self getHighScore10]];
	[obj setDailyHighScore01:[self getDailyHighScore01]];
	[obj setDailyHighScore02:[self getDailyHighScore02]];
	[obj setDailyHighScore03:[self getDailyHighScore03]];
	[obj setDailyHighScore04:[self getDailyHighScore04]];
	[obj setDailyHighScore05:[self getDailyHighScore05]];
	[obj setDailyHighScore06:[self getDailyHighScore06]];
	[obj setDailyHighScore07:[self getDailyHighScore07]];
	[obj setDailyHighScore08:[self getDailyHighScore08]];
	[obj setDailyHighScore09:[self getDailyHighScore09]];
	[obj setDailyHighScore10:[self getDailyHighScore10]];
	[obj setWeeklyHighScore01:[self getWeeklyHighScore01]];
	[obj setWeeklyHighScore02:[self getWeeklyHighScore02]];
	[obj setWeeklyHighScore03:[self getWeeklyHighScore03]];
	[obj setWeeklyHighScore04:[self getWeeklyHighScore04]];
	[obj setWeeklyHighScore05:[self getWeeklyHighScore05]];
	[obj setWeeklyHighScore06:[self getWeeklyHighScore06]];
	[obj setWeeklyHighScore07:[self getWeeklyHighScore07]];
	[obj setWeeklyHighScore08:[self getWeeklyHighScore08]];
	[obj setWeeklyHighScore09:[self getWeeklyHighScore09]];
	[obj setWeeklyHighScore10:[self getWeeklyHighScore10]];
	[obj setLastDailyHighScore01:[self getLastDailyHighScore01]];
	[obj setLastDailyHighScore02:[self getLastDailyHighScore02]];
	[obj setLastDailyHighScore03:[self getLastDailyHighScore03]];
	[obj setLastDailyHighScore04:[self getLastDailyHighScore04]];
	[obj setLastDailyHighScore05:[self getLastDailyHighScore05]];
	[obj setLastDailyHighScore06:[self getLastDailyHighScore06]];
	[obj setLastDailyHighScore07:[self getLastDailyHighScore07]];
	[obj setLastDailyHighScore08:[self getLastDailyHighScore08]];
	[obj setLastDailyHighScore09:[self getLastDailyHighScore09]];
	[obj setLastDailyHighScore10:[self getLastDailyHighScore10]];
	[obj setLastWeeklyHighScore01:[self getLastWeeklyHighScore01]];
	[obj setLastWeeklyHighScore02:[self getLastWeeklyHighScore02]];
	[obj setLastWeeklyHighScore03:[self getLastWeeklyHighScore03]];
	[obj setLastWeeklyHighScore04:[self getLastWeeklyHighScore04]];
	[obj setLastWeeklyHighScore05:[self getLastWeeklyHighScore05]];
	[obj setLastWeeklyHighScore06:[self getLastWeeklyHighScore06]];
	[obj setLastWeeklyHighScore07:[self getLastWeeklyHighScore07]];
	[obj setLastWeeklyHighScore08:[self getLastWeeklyHighScore08]];
	[obj setLastWeeklyHighScore09:[self getLastWeeklyHighScore09]];
	[obj setLastWeeklyHighScore10:[self getLastWeeklyHighScore10]];

	return [obj autorelease];
}
- (void) dealloc
{
	[m_ID release];
	m_ID = nil;
	[m_UserId release];
	m_UserId = nil;
	[m_GameId release];
	m_GameId = nil;
	[m_UserName release];
	m_UserName = nil;
	[m_AvatarUrl release];
	m_AvatarUrl = nil;
	[m_Token release];
	m_Token = nil;
	[m_Currency01 release];
	m_Currency01 = nil;
	[m_Currency02 release];
	m_Currency02 = nil;
	[m_Currency03 release];
	m_Currency03 = nil;
	[m_ArchivementCount01 release];
	m_ArchivementCount01 = nil;
	[m_ArchivementCount02 release];
	m_ArchivementCount02 = nil;
	[m_ArchivementCount03 release];
	m_ArchivementCount03 = nil;
	[m_ArchivementCount04 release];
	m_ArchivementCount04 = nil;
	[m_ArchivementCount05 release];
	m_ArchivementCount05 = nil;
	[m_HighScore01 release];
	m_HighScore01 = nil;
	[m_HighScore02 release];
	m_HighScore02 = nil;
	[m_HighScore03 release];
	m_HighScore03 = nil;
	[m_HighScore04 release];
	m_HighScore04 = nil;
	[m_HighScore05 release];
	m_HighScore05 = nil;
	[m_HighScore06 release];
	m_HighScore06 = nil;
	[m_HighScore07 release];
	m_HighScore07 = nil;
	[m_HighScore08 release];
	m_HighScore08 = nil;
	[m_HighScore09 release];
	m_HighScore09 = nil;
	[m_HighScore10 release];
	m_HighScore10 = nil;
	[m_DailyHighScore01 release];
	m_DailyHighScore01 = nil;
	[m_DailyHighScore02 release];
	m_DailyHighScore02 = nil;
	[m_DailyHighScore03 release];
	m_DailyHighScore03 = nil;
	[m_DailyHighScore04 release];
	m_DailyHighScore04 = nil;
	[m_DailyHighScore05 release];
	m_DailyHighScore05 = nil;
	[m_DailyHighScore06 release];
	m_DailyHighScore06 = nil;
	[m_DailyHighScore07 release];
	m_DailyHighScore07 = nil;
	[m_DailyHighScore08 release];
	m_DailyHighScore08 = nil;
	[m_DailyHighScore09 release];
	m_DailyHighScore09 = nil;
	[m_DailyHighScore10 release];
	m_DailyHighScore10 = nil;
	[m_WeeklyHighScore01 release];
	m_WeeklyHighScore01 = nil;
	[m_WeeklyHighScore02 release];
	m_WeeklyHighScore02 = nil;
	[m_WeeklyHighScore03 release];
	m_WeeklyHighScore03 = nil;
	[m_WeeklyHighScore04 release];
	m_WeeklyHighScore04 = nil;
	[m_WeeklyHighScore05 release];
	m_WeeklyHighScore05 = nil;
	[m_WeeklyHighScore06 release];
	m_WeeklyHighScore06 = nil;
	[m_WeeklyHighScore07 release];
	m_WeeklyHighScore07 = nil;
	[m_WeeklyHighScore08 release];
	m_WeeklyHighScore08 = nil;
	[m_WeeklyHighScore09 release];
	m_WeeklyHighScore09 = nil;
	[m_WeeklyHighScore10 release];
	m_WeeklyHighScore10 = nil;
	[m_LastDailyHighScore01 release];
	m_LastDailyHighScore01 = nil;
	[m_LastDailyHighScore02 release];
	m_LastDailyHighScore02 = nil;
	[m_LastDailyHighScore03 release];
	m_LastDailyHighScore03 = nil;
	[m_LastDailyHighScore04 release];
	m_LastDailyHighScore04 = nil;
	[m_LastDailyHighScore05 release];
	m_LastDailyHighScore05 = nil;
	[m_LastDailyHighScore06 release];
	m_LastDailyHighScore06 = nil;
	[m_LastDailyHighScore07 release];
	m_LastDailyHighScore07 = nil;
	[m_LastDailyHighScore08 release];
	m_LastDailyHighScore08 = nil;
	[m_LastDailyHighScore09 release];
	m_LastDailyHighScore09 = nil;
	[m_LastDailyHighScore10 release];
	m_LastDailyHighScore10 = nil;
	[m_LastWeeklyHighScore01 release];
	m_LastWeeklyHighScore01 = nil;
	[m_LastWeeklyHighScore02 release];
	m_LastWeeklyHighScore02 = nil;
	[m_LastWeeklyHighScore03 release];
	m_LastWeeklyHighScore03 = nil;
	[m_LastWeeklyHighScore04 release];
	m_LastWeeklyHighScore04 = nil;
	[m_LastWeeklyHighScore05 release];
	m_LastWeeklyHighScore05 = nil;
	[m_LastWeeklyHighScore06 release];
	m_LastWeeklyHighScore06 = nil;
	[m_LastWeeklyHighScore07 release];
	m_LastWeeklyHighScore07 = nil;
	[m_LastWeeklyHighScore08 release];
	m_LastWeeklyHighScore08 = nil;
	[m_LastWeeklyHighScore09 release];
	m_LastWeeklyHighScore09 = nil;
	[m_LastWeeklyHighScore10 release];
	m_LastWeeklyHighScore10 = nil;
	
	[super dealloc];
}

@end
/**
 * @interface:SentRequestDto
 * @key:ID
 */
@implementation PineHighScore_DataTransferObjects_SentRequestDto
	@synthesize m_ID;
	@synthesize m_GameId;
	@synthesize m_Sender;
	@synthesize m_Receiver;
	@synthesize m_RequestType;

/**
 *Method to create an instance of SentRequestDto
 */
+ (id) CreateSentRequestDtoWithid:(NSNumber *)aID gameid:(NSNumber *)aGameId sender:(NSNumber *)aSender receiver:(NSNumber *)aReceiver requesttype:(NSNumber *)aRequestType
{
	PineHighScore_DataTransferObjects_SentRequestDto *aSentRequestDto = [[PineHighScore_DataTransferObjects_SentRequestDto alloc]init];
	
	aSentRequestDto.m_ID = aID;

	
	aSentRequestDto.m_GameId = aGameId;

	
	aSentRequestDto.m_Sender = aSender;

	
	aSentRequestDto.m_Receiver = aReceiver;

	
	aSentRequestDto.m_RequestType = aRequestType;

	return aSentRequestDto;
}
/**
 * Initialising object for SentRequestDto
 */
- (id) init
{
	self=[self initWithUri:nil];
	return self;
}

- (id) initWithUri:(NSString*)anUri 
{
	if(self=[super initWithUri:anUri])
	{
		[self setBaseURI:anUri];
		m_OData_hasStream.booleanvalue=NO;
		mProperties *obj;
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_ID"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_GameId"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_Sender"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_Receiver"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int32" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_RequestType"];
		[obj release];
		

		NSMutableArray *anEntityKey=[[NSMutableArray alloc]init];
		[anEntityKey addObject:@"ID"];
		[m_OData_entityKey setObject:anEntityKey forKey:@"SentRequestDto"];
		[anEntityKey release];
	}
	return self;
}

-(NSMutableArray *)getSyndicateArray
{
	NSMutableArray *syndicateArray=[[NSMutableArray alloc]init];
	
	return [syndicateArray autorelease];
}
-(PineHighScore_DataTransferObjects_SentRequestDto *)getDeepCopy
{
	PineHighScore_DataTransferObjects_SentRequestDto *obj=[[PineHighScore_DataTransferObjects_SentRequestDto alloc]initWithUri:[self getBaseURI]];
	[obj setID:[self getID]];
	[obj setGameId:[self getGameId]];
	[obj setSender:[self getSender]];
	[obj setReceiver:[self getReceiver]];
	[obj setRequestType:[self getRequestType]];

	return [obj autorelease];
}
- (void) dealloc
{
	[m_ID release];
	m_ID = nil;
	[m_GameId release];
	m_GameId = nil;
	[m_Sender release];
	m_Sender = nil;
	[m_Receiver release];
	m_Receiver = nil;
	[m_RequestType release];
	m_RequestType = nil;
	
	[super dealloc];
}

@end
/**
 * @interface:RankedHighScoreDto
 * @key:ID
 */
@implementation PineHighScore_DataTransferObjects_RankedHighScoreDto
	@synthesize m_ID;
	@synthesize m_Rank;
	@synthesize m_UserId;
	@synthesize m_Score;
	@synthesize m_TopScore;

/**
 *Method to create an instance of RankedHighScoreDto
 */
+ (id) CreateRankedHighScoreDtoWithid:(NSString *)aID rank:(NSNumber *)aRank userid:(NSNumber *)aUserId
{
	PineHighScore_DataTransferObjects_RankedHighScoreDto *aRankedHighScoreDto = [[PineHighScore_DataTransferObjects_RankedHighScoreDto alloc]init];
	
	aRankedHighScoreDto.m_ID = aID;

	
	aRankedHighScoreDto.m_Rank = aRank;

	
	aRankedHighScoreDto.m_UserId = aUserId;

	return aRankedHighScoreDto;
}
/**
 * Initialising object for RankedHighScoreDto
 */
- (id) init
{
	self=[self initWithUri:nil];
	return self;
}

- (id) initWithUri:(NSString*)anUri 
{
	if(self=[super initWithUri:anUri])
	{
		[self setBaseURI:anUri];
		m_OData_hasStream.booleanvalue=NO;
		mProperties *obj;
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Guid" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_ID"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int32" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_Rank"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_UserId"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_Score"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_TopScore"];
		[obj release];
		

		NSMutableArray *anEntityKey=[[NSMutableArray alloc]init];
		[anEntityKey addObject:@"ID"];
		[m_OData_entityKey setObject:anEntityKey forKey:@"RankedHighScoreDto"];
		[anEntityKey release];
	}
	return self;
}

-(NSMutableArray *)getSyndicateArray
{
	NSMutableArray *syndicateArray=[[NSMutableArray alloc]init];
	
	return [syndicateArray autorelease];
}
-(PineHighScore_DataTransferObjects_RankedHighScoreDto *)getDeepCopy
{
	PineHighScore_DataTransferObjects_RankedHighScoreDto *obj=[[PineHighScore_DataTransferObjects_RankedHighScoreDto alloc]initWithUri:[self getBaseURI]];
	[obj setID:[self getID]];
	[obj setRank:[self getRank]];
	[obj setUserId:[self getUserId]];
	[obj setScore:[self getScore]];
	[obj setTopScore:[self getTopScore]];

	return [obj autorelease];
}
- (void) dealloc
{
	[m_ID release];
	m_ID = nil;
	[m_Rank release];
	m_Rank = nil;
	[m_UserId release];
	m_UserId = nil;
	[m_Score release];
	m_Score = nil;
	[m_TopScore release];
	m_TopScore = nil;
	
	[super dealloc];
}

@end
/**
 * @interface:TopScoreDto
 * @key:ID
 */
@implementation PineHighScore_DataTransferObjects_TopScoreDto
	@synthesize m_ID;
	@synthesize m_UserId;
	@synthesize m_UserName;
	@synthesize m_AvatarUrl;
	@synthesize m_Score;

/**
 *Method to create an instance of TopScoreDto
 */
+ (id) CreateTopScoreDtoWithid:(NSString *)aID userid:(NSNumber *)aUserId
{
	PineHighScore_DataTransferObjects_TopScoreDto *aTopScoreDto = [[PineHighScore_DataTransferObjects_TopScoreDto alloc]init];
	
	aTopScoreDto.m_ID = aID;

	
	aTopScoreDto.m_UserId = aUserId;

	return aTopScoreDto;
}
/**
 * Initialising object for TopScoreDto
 */
- (id) init
{
	self=[self initWithUri:nil];
	return self;
}

- (id) initWithUri:(NSString*)anUri 
{
	if(self=[super initWithUri:anUri])
	{
		[self setBaseURI:anUri];
		m_OData_hasStream.booleanvalue=NO;
		mProperties *obj;
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Guid" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_ID"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Int64" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:NO Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_UserId"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.String" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_UserName"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.String" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_AvatarUrl"];
		[obj release];
		
		obj=[[mProperties alloc]initWithEdmType:@"Edm.Double" MaxLength:@"" MinLength:@"" FixedLength:NO Nullable:YES Unicode:NO ConcurrencyMode:@"" FC_TargetPath:@"" FC_KeepInContent:YES FC_SourcePath:@"" FC_ContentKind:@"" FC_NsPrefix:@"" FC_NsUri:@""];
		[m_OData_propertiesMap setObject:obj forKey:@"m_Score"];
		[obj release];
		

		NSMutableArray *anEntityKey=[[NSMutableArray alloc]init];
		[anEntityKey addObject:@"ID"];
		[m_OData_entityKey setObject:anEntityKey forKey:@"TopScoreDto"];
		[anEntityKey release];
	}
	return self;
}

-(NSMutableArray *)getSyndicateArray
{
	NSMutableArray *syndicateArray=[[NSMutableArray alloc]init];
	
	return [syndicateArray autorelease];
}
-(PineHighScore_DataTransferObjects_TopScoreDto *)getDeepCopy
{
	PineHighScore_DataTransferObjects_TopScoreDto *obj=[[PineHighScore_DataTransferObjects_TopScoreDto alloc]initWithUri:[self getBaseURI]];
	[obj setID:[self getID]];
	[obj setUserId:[self getUserId]];
	[obj setUserName:[self getUserName]];
	[obj setAvatarUrl:[self getAvatarUrl]];
	[obj setScore:[self getScore]];

	return [obj autorelease];
}
- (void) dealloc
{
	[m_ID release];
	m_ID = nil;
	[m_UserId release];
	m_UserId = nil;
	[m_UserName release];
	m_UserName = nil;
	[m_AvatarUrl release];
	m_AvatarUrl = nil;
	[m_Score release];
	m_Score = nil;
	
	[super dealloc];
}

@end

 
/**
 * Container interface PineHighScoreContext, Namespace: PineHighScore.DataTransferObjects
 */
@implementation PineHighScoreContext 

	@synthesize m_OData_etag;

	@synthesize m_HighScores;
	@synthesize m_MyRequests;
	@synthesize m_RankedScores;
	@synthesize m_TopScores;
/**
 * The initializer for PineHighScoreContext accepting service URI
 */
- (id) init
{
	NSString* tmpuri =[[NSString alloc]initWithString:DEFAULT_SERVICE_URL];
	self=[self initWithUri:tmpuri credential:nil];
	[tmpuri release];
	return self;
}

- (id) initWithUri:(NSString*)anUri credential:(id)acredential
{
	NSString* tmpuri=nil;
	if([anUri length]==0)
	{
	 	tmpuri = DEFAULT_SERVICE_URL;
	}
	else
	{
		tmpuri =[NSString stringWithString:anUri];
	}
	if(![tmpuri hasSuffix:@"/"])
	{
		tmpuri=[tmpuri stringByAppendingString:@"/"];
	}

	if(self=[super initWithUri:tmpuri credentials:acredential dataServiceVersion:DataServiceVersion])
	{
		[super setServiceNamespace:@"PineHighScore.DataTransferObjects"];

		NSMutableArray* tempEntities=[[NSMutableArray alloc]init];
		
		[tempEntities addObject:@"HighScores"];
		[tempEntities addObject:@"MyRequests"];
		[tempEntities addObject:@"RankedScores"];
		[tempEntities addObject:@"TopScores"];

		if([tempEntities count] > 0 )
		{
			[super setEntitiesWithArray:tempEntities];
		}
		[tempEntities release];

		NSMutableArray* tempEntitiySetKey=[[NSMutableArray alloc]init];
		
		[tempEntitiySetKey addObject:@"highscores"];
		[tempEntitiySetKey addObject:@"myrequests"];
		[tempEntitiySetKey addObject:@"rankedscores"];
		[tempEntitiySetKey addObject:@"topscores"];

		NSMutableArray* tempEntitiyTypeobj=[[NSMutableArray alloc]init];
		
		[tempEntitiyTypeobj addObject:@"HighScoreDto"];
		[tempEntitiyTypeobj addObject:@"SentRequestDto"];
		[tempEntitiyTypeobj addObject:@"RankedHighScoreDto"];
		[tempEntitiyTypeobj addObject:@"TopScoreDto"];

		if( ( [tempEntitiySetKey count] > 0 ) && ( [tempEntitiyTypeobj count] > 0 ) )
		{
			[super setEntitySet2TypeWithObject:tempEntitiyTypeobj forKey:tempEntitiySetKey];

		}

		[tempEntitiySetKey release];
		[ tempEntitiyTypeobj release];

		NSMutableArray* tempEntitiyTypeKey=[[NSMutableArray alloc]init];
		
		[tempEntitiyTypeKey addObject:@"highscoredto"];
		[tempEntitiyTypeKey addObject:@"sentrequestdto"];
		[tempEntitiyTypeKey addObject:@"rankedhighscoredto"];
		[tempEntitiyTypeKey addObject:@"topscoredto"];
		NSMutableArray* tempEntitySetObj=[[NSMutableArray alloc]init];
		
		[tempEntitySetObj addObject:@"HighScores"];
		[tempEntitySetObj addObject:@"MyRequests"];
		[tempEntitySetObj addObject:@"RankedScores"];
		[tempEntitySetObj addObject:@"TopScores"];

		if( ( [tempEntitiyTypeKey count] > 0 ) && ( [tempEntitySetObj count] > 0 ) )
		{
			[super setEntityType2SetWithObject:tempEntitySetObj forKey:tempEntitiyTypeKey];

		}
    	[tempEntitiyTypeKey release];
		[tempEntitySetObj release];

		NSMutableArray* foreignKeys=[[NSMutableArray alloc]init];		

		NSMutableArray *arrOfDictionaries=[[NSMutableArray alloc]initWithCapacity:[foreignKeys count]];
		if( ( [foreignKeys count] > 0 ) && ( [arrOfDictionaries count] > 0 ) )
		{
			[super setAssociationforObjects:arrOfDictionaries forKeys:foreignKeys];
		}
		[foreignKeys release];
		[arrOfDictionaries release];

		m_HighScores = [[DataServiceQuery alloc]initWithUri:@"HighScores" objectContext: self];
		m_MyRequests = [[DataServiceQuery alloc]initWithUri:@"MyRequests" objectContext: self];
		m_RankedScores = [[DataServiceQuery alloc]initWithUri:@"RankedScores" objectContext: self];
		m_TopScores = [[DataServiceQuery alloc]initWithUri:@"TopScores" objectContext: self];
		
	}
	return self;
}


/**
 * Method returns DataServiceQuery reference for
 * the entityset HighScores
 */
- (id) highscores
{
	[self.m_HighScores clearAllOptions];
	return self.m_HighScores;
}

/**
 * Method returns DataServiceQuery reference for
 * the entityset MyRequests
 */
- (id) myrequests
{
	[self.m_MyRequests clearAllOptions];
	return self.m_MyRequests;
}

/**
 * Method returns DataServiceQuery reference for
 * the entityset RankedScores
 */
- (id) rankedscores
{
	[self.m_RankedScores clearAllOptions];
	return self.m_RankedScores;
}

/**
 * Method returns DataServiceQuery reference for
 * the entityset TopScores
 */
- (id) topscores
{
	[self.m_TopScores clearAllOptions];
	return self.m_TopScores;
}

/**
 * Methods for adding object to the entityset/collection
 */

- (void) addToHighScores:(id)anObject
{
	[super addObject:@"HighScores" object:anObject];
}

- (void) addToMyRequests:(id)anObject
{
	[super addObject:@"MyRequests" object:anObject];
}

- (void) addToRankedScores:(id)anObject
{
	[super addObject:@"RankedScores" object:anObject];
}

- (void) addToTopScores:(id)anObject
{
	[super addObject:@"TopScores" object:anObject];
}

- (void) dealloc
{
	[ m_OData_etag release];
	m_OData_etag = nil;
	
	[m_HighScores release];
	m_HighScores = nil;
	[m_MyRequests release];
	m_MyRequests = nil;
	[m_RankedScores release];
	m_RankedScores = nil;
	[m_TopScores release];
	m_TopScores = nil;

	[super dealloc];
}

@end
