//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 1/5/2015 5:24:35 PM
namespace Pine.WildWildWestServer
{
    
    /// <summary>
    /// There are no comments for WildWildWestContext in the schema.
    /// </summary>
    public partial class WildWildWestContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new WildWildWestContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public WildWildWestContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "WildWildWest.DataTransferObjects", "Pine.WildWildWestServer");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Pine.WildWildWestServer", global::System.StringComparison.Ordinal))
            {
                return string.Concat("WildWildWest.DataTransferObjects.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for SaveGames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SaveGameDto> SaveGames
        {
            get
            {
                if ((this._SaveGames == null))
                {
                    this._SaveGames = base.CreateQuery<SaveGameDto>("SaveGames");
                }
                return this._SaveGames;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SaveGameDto> _SaveGames;
        /// <summary>
        /// There are no comments for Statistics in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<StatisticDto> Statistics
        {
            get
            {
                if ((this._Statistics == null))
                {
                    this._Statistics = base.CreateQuery<StatisticDto>("Statistics");
                }
                return this._Statistics;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<StatisticDto> _Statistics;
        /// <summary>
        /// There are no comments for SaveGames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSaveGames(SaveGameDto saveGameDto)
        {
            base.AddObject("SaveGames", saveGameDto);
        }
        /// <summary>
        /// There are no comments for Statistics in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStatistics(StatisticDto statisticDto)
        {
            base.AddObject("Statistics", statisticDto);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = @"<edmx:Edmx Version=""1.0"" xmlns:edmx=""http://schemas.microsoft.com/ado/2007/06/edmx""><edmx:DataServices m:DataServiceVersion=""3.0"" m:MaxDataServiceVersion=""3.0"" xmlns:m=""http://schemas.microsoft.com/ado/2007/08/dataservices/metadata""><Schema Namespace=""WildWildWest.DataTransferObjects"" xmlns=""http://schemas.microsoft.com/ado/2009/11/edm""><EntityType Name=""SaveGameDto""><Key><PropertyRef Name=""ID"" /></Key><Property Name=""ID"" Type=""Edm.Int64"" Nullable=""false"" /><Property Name=""UserName"" Type=""Edm.String"" /><Property Name=""AvatarUrl"" Type=""Edm.String"" /><Property Name=""HighScore"" Type=""Edm.Int32"" Nullable=""false"" /><Property Name=""Money"" Type=""Edm.Int32"" Nullable=""false"" /><Property Name=""Location"" Type=""Edm.Int16"" Nullable=""false"" /><Property Name=""Data"" Type=""Edm.Binary"" /></EntityType><EntityType Name=""StatisticDto""><Key><PropertyRef Name=""ID"" /></Key><Property Name=""ID"" Type=""Edm.String"" Nullable=""false"" /><Property Name=""TotalUsers"" Type=""Edm.Int32"" Nullable=""false"" /><Property Name=""ActiveUsers"" Type=""Edm.Int32"" Nullable=""false"" /></EntityType></Schema><Schema Namespace=""Default"" xmlns=""http://schemas.microsoft.com/ado/2009/11/edm""><EntityContainer Name=""WildWildWestContext"" m:IsDefaultEntityContainer=""true""><EntitySet Name=""SaveGames"" EntityType=""WildWildWest.DataTransferObjects.SaveGameDto"" /><EntitySet Name=""Statistics"" EntityType=""WildWildWest.DataTransferObjects.StatisticDto"" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for WildWildWest.DataTransferObjects.SaveGameDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SaveGames")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class SaveGameDto : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SaveGameDto object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="highScore">Initial value of HighScore.</param>
        /// <param name="money">Initial value of Money.</param>
        /// <param name="location">Initial value of Location.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SaveGameDto CreateSaveGameDto(long ID, int highScore, int money, short location)
        {
            SaveGameDto saveGameDto = new SaveGameDto();
            saveGameDto.ID = ID;
            saveGameDto.HighScore = highScore;
            saveGameDto.Money = money;
            saveGameDto.Location = location;
            return saveGameDto;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property AvatarUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AvatarUrl
        {
            get
            {
                return this._AvatarUrl;
            }
            set
            {
                this.OnAvatarUrlChanging(value);
                this._AvatarUrl = value;
                this.OnAvatarUrlChanged();
                this.OnPropertyChanged("AvatarUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AvatarUrl;
        partial void OnAvatarUrlChanging(string value);
        partial void OnAvatarUrlChanged();
        /// <summary>
        /// There are no comments for Property HighScore in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int HighScore
        {
            get
            {
                return this._HighScore;
            }
            set
            {
                this.OnHighScoreChanging(value);
                this._HighScore = value;
                this.OnHighScoreChanged();
                this.OnPropertyChanged("HighScore");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _HighScore;
        partial void OnHighScoreChanging(int value);
        partial void OnHighScoreChanged();
        /// <summary>
        /// There are no comments for Property Money in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Money
        {
            get
            {
                return this._Money;
            }
            set
            {
                this.OnMoneyChanging(value);
                this._Money = value;
                this.OnMoneyChanged();
                this.OnPropertyChanged("Money");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Money;
        partial void OnMoneyChanging(int value);
        partial void OnMoneyChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _Location;
        partial void OnLocationChanging(short value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Data
        {
            get
            {
                if ((this._Data != null))
                {
                    return ((byte[])(this._Data.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnDataChanging(value);
                this._Data = value;
                this.OnDataChanged();
                this.OnPropertyChanged("Data");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Data;
        partial void OnDataChanging(byte[] value);
        partial void OnDataChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for WildWildWest.DataTransferObjects.StatisticDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Statistics")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class StatisticDto : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new StatisticDto object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="totalUsers">Initial value of TotalUsers.</param>
        /// <param name="activeUsers">Initial value of ActiveUsers.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static StatisticDto CreateStatisticDto(string ID, int totalUsers, int activeUsers)
        {
            StatisticDto statisticDto = new StatisticDto();
            statisticDto.ID = ID;
            statisticDto.TotalUsers = totalUsers;
            statisticDto.ActiveUsers = activeUsers;
            return statisticDto;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ID;
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property TotalUsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TotalUsers
        {
            get
            {
                return this._TotalUsers;
            }
            set
            {
                this.OnTotalUsersChanging(value);
                this._TotalUsers = value;
                this.OnTotalUsersChanged();
                this.OnPropertyChanged("TotalUsers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TotalUsers;
        partial void OnTotalUsersChanging(int value);
        partial void OnTotalUsersChanged();
        /// <summary>
        /// There are no comments for Property ActiveUsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ActiveUsers
        {
            get
            {
                return this._ActiveUsers;
            }
            set
            {
                this.OnActiveUsersChanging(value);
                this._ActiveUsers = value;
                this.OnActiveUsersChanged();
                this.OnPropertyChanged("ActiveUsers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ActiveUsers;
        partial void OnActiveUsersChanging(int value);
        partial void OnActiveUsersChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
